### PR TITLE
Add "api" string enum field to shared info

### PR DESCRIPTION
**Pull request by alexmturner**
Allows for the aggregation service to support multiple APIs in the future

### CODE REVIEW

**Comment by csharrison** [comment]
What do you think about shortening the API string to save bytes on disk?

**Comment by alexmturner** [comment]
We could try something like "attribution" instead. That being said, I'm not sure how valuable shortening is given the length of some of our other keys/values. So I'd have a slight preference to leaving it as is, but happy either way.

**Review by csharrison — APPROVED** [review]
I think this is fine.

**Comment by johnivdel** [comment]
I do like that `attribution-reporting` matches the permission policy name. But even something like `ara` (to distinguish from augmented reality) seems very reasonable imo. This will also save bandwidth for the browser and the developer when uploading batches.

My expectation is the main consumer of this field will be the aggregation service, rather than the developer who is getting reports on an api specific endpoint. Going with the shortened version seems like it is serving everyones interests. The aggregation service is complicated enough that a more obfuscated name should be manageable.

**Comment by alexmturner** [comment]
I think let's stick with "attribution-reporting" then; this better aligns with the "common words" and "consistency" naming principles (https://www.w3.org/TR/design-principles/#naming-is-hard)

**Pull request merged**
