### PR TITLE
Explanation of the enumeration of the output states

### PR DESCRIPTION
**Pull request by alois-bissuel**
Adding a quite detailed explanation of the enumeration of the output states, including a short intro to the stars and bars method. Slightly verbose, and it could be well shortened if needed.

### CODE REVIEW

**Comment by alois-bissuel** [comment]
Oups, I had never linked my GitHub account to my W3C one. This is done now, I hope that the checks will pass now.

**Comment by csharrison** [comment]
> Oups, I had never linked my GitHub account to my W3C one. This is done now, I hope that the checks will pass now.

Hm, I tried revalidating the IPR bot and they still think the PR is unacceptable. Can you make sure you also join the WICG? I don't see you [here](https://www.w3.org/community/wicg/participants).

**Comment by alois-bissuel** [comment]
Thanks Charlie, I created a request for joining the WICG, I hope it will be validated soon!

**Comment by csharrison** [comment]
I actually think this technically a "non-substantive" change as we're just fleshing out a non-normative section with a derivation, so we can merge it before your WICG membership goes through.

**Pull request merged**
